zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle :compinstall filename '/home/kyle/.zshrc'

autoload -Uz compinit
compinit

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd beep extendedglob nomatch notify
bindkey -v

source "$HOME/.antigen.zsh"

antigen use oh-my-zsh

antigen bundle https://github.com/spwhitt/nix-zsh-completions.git

antigen theme lambda

antigen apply
